language: cpp

compiler:
  - gcc

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - cmake
    - g++-4.8
    - gfortran-4.8
    - libx11-dev
    - libxft-dev
    - libxext-dev
    - liblzma-dev

cache:
  directories:
    - $HOME/cache

before-script:
  export CC="gcc-4.8" CXX="g++-4.8" FC="gfortran-4.8"
  
script: ./.travis.build.sh
