language: cpp

compiler:
  - gcc

sudo: false
  
addons:
  apt:
    packages:
    - build-essential
    - gfortran
    - libx11-dev
    - libxft-dev
    - libxext-dev
    - liblzma-dev

cache:
  directories:
    - $HOME/cache
  
script: ./.travis.build.sh

after_success:
  - cd build && make coveralls
  - bash <(curl -s https://codecov.io/bash)
